package com.davis.hospital_Appointment_Rest_API.model;

import java.time.LocalDateTime;
import java.time.LocalTime;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.davis.hospital_Appointment_Rest_API.utils.LocalTimeDeserializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a doctor's schedule in the Hospital Appointment System.
 * <p>
 * This entity maps a doctor's availability for appointments on specific days,
 * including their working hours, maximum appointment capacity, and availability
 * confirmation status. Each schedule entry defines when a doctor is available
 * for appointments on a particular day of the week.
 * </p>
 * 
 * <p><b>Relationships:</b>
 * <ul>
 *   <li>Many-to-one relationship with {@link Doctor}</li>
 * </ul>
 * </p>
 * 
 * <p><b>Table Structure:</b>
 * <ul>
 *   <li>Doctor_Schedule - Stores all doctor schedule entries</li>
 * </ul>
 * </p>
 * 
 * @author CYPRIAN DAVIS
 * @version 1.0
 * @since 2025-06-03
 * @see Doctor
 */
@Entity
@Table(name = "Doctor_Schedule")
public class DoctorSchedule {
    
    /**
     * The unique primary key identifier for this schedule entry.
     * <p>
     * Automatically generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * The doctor associated with this schedule entry.
     * <p>
     * Represents a many-to-one relationship with the Doctor entity,
     * using doctorId as the foreign key.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "doctorId")
    private Doctor doctor;
    
    /**
     * The day of the week for this schedule entry.
     * <p>
     * Expected values: "Monday", "Tuesday", etc.
     * </p>
     */
    private String dayOfWeek;
    
    /**
     * The start time of the doctor's availability window.
     * <p>
     * Uses Java 8 {@link LocalTime} to represent time without date.
     * </p>
     */
    @JsonDeserialize(using = LocalTimeDeserializer.class)
    private LocalTime startTime;
    
    /**
     * The end time of the doctor's availability window.
     * <p>
     * Uses Java 8 {@link LocalTime} to represent time without date.
     * </p>
     */
    @JsonDeserialize(using = LocalTimeDeserializer.class)
    private LocalTime endTime;
    
    /**
     * The number of available appointment slots during this time period.
     * <p>
     * Calculated based on the time window and accounting for breaks.
     * </p>
     */
    private int availableSlots;
    
    /**
     * Indicates whether the doctor has confirmed their availability.
     * <p>
     * Defaults to false (unconfirmed). When true, the schedule is
     * guaranteed to be available for appointments.
     * </p>
     */
    private boolean isConfirmed;
    
    /**
     * The timestamp when this schedule entry was created.
     * <p>
     * Automatically set when the schedule is first persisted.
     * </p>
     */
    @CreationTimestamp
    private LocalDateTime createdOn;
    
    /**
     * The timestamp when this schedule entry was last modified.
     * <p>
     * Updated whenever any field in the schedule is changed.
     * </p>
     */
    @UpdateTimestamp
    private LocalDateTime lastUpdated;

    /**
     * Constructs a new DoctorSchedule with the specified parameters.
     *
     * @param doctor the doctor associated with this schedule (cannot be null)
     * @param dayOfWeek the day of the week (e.g., "Monday", "Tuesday")
     * @param startTime the start time of availability window (cannot be null)
     * @param endTime the end time of availability window (cannot be null)
     * @param maximumAppointments the maximum number of appointments allowed (must be positive)
     */
    public DoctorSchedule(Doctor doctor, String dayOfWeek, LocalTime startTime, LocalTime endTime,
            int maximumAppointments) {
        this.doctor = doctor;
        this.dayOfWeek = dayOfWeek;
        this.startTime = startTime;
        this.endTime = endTime;
        this.availableSlots = maximumAppointments;
    }

    /**
     * Default constructor required by JPA.
     */
    public DoctorSchedule() {}

    /**
     * Gets the unique identifier of this schedule entry.
     *
     * @return the schedule ID, or null if not persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this schedule entry.
     * <p>
     * Note: Typically only used by JPA, not for business logic.
     * </p>
     *
     * @param id the ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the doctor associated with this schedule.
     *
     * @return the associated Doctor entity
     */
    public Doctor getDoctor() {
        return doctor;
    }

    /**
     * Sets the doctor associated with this schedule.
     *
     * @param doctor the Doctor to associate with this schedule
     */
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

    /**
     * Gets the day of the week for this schedule.
     *
     * @return the day of week (e.g., "Monday")
     */
    public String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the day of the week for this schedule.
     *
     * @param dayOfWeek the day of week to set (e.g., "Monday")
     */
    public void setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * Gets the start time of availability window.
     *
     * @return the start time, never null
     */
    public LocalTime getStartTime() {
        return startTime;
    }

    /**
     * Sets the start time of availability window.
     *
     * @param startTime the start time to set (cannot be null)
     */
    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }

    /**
     * Gets the end time of availability window.
     *
     * @return the end time, never null
     */
    public LocalTime getEndTime() {
        return endTime;
    }

    /**
     * Sets the end time of availability window.
     *
     * @param endTime the end time to set (cannot be null)
     */
    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }


    /**
     * Gets the number of available appointment slots.
     *
     * @return the number of available slots
     */
    public int getAvailableSlots() {
        return availableSlots;
    }

    /**
     * Sets the number of available appointment slots.
     *
     * @param availableSlots the number of slots to set (must be positive)
     * @throws IllegalArgumentException if availableSlots is negative
     */
    public void setAvailableSlots(int availableSlots) {
       
        this.availableSlots = availableSlots;
    }

    /**
     * Checks if the doctor has confirmed this schedule.
     *
     * @return true if the schedule is confirmed, false otherwise
     */
    public boolean isConfirmed() {
        return isConfirmed;
    }

    /**
     * Sets the confirmation status of this schedule.
     *
     * @param isConfirmed the confirmation status to set
     */
    public void setConfirmed(boolean isConfirmed) {
        this.isConfirmed = isConfirmed;
    }

    /**
     * Gets the creation timestamp of this schedule.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedOn() {
        return createdOn;
    }

    /**
     * Sets the creation timestamp of this schedule.
     * <p>
     * Note: Typically only used by JPA, not for business logic.
     * </p>
     *
     * @param createdOn the creation timestamp to set
     */
    public void setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * Gets the last updated timestamp of this schedule.
     *
     * @return the last update timestamp
     */
    public LocalDateTime getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Sets the last updated timestamp of this schedule.
     *
     * @param lastUpdated the update timestamp to set
     */
    public void setLastUpdated(LocalDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}